#!/usr/bin/env python3
"""
HL Copy Trading - Main Orchestrator
Coordinates leaderboard scanning, fill monitoring, and copy execution.
"""
import json
import time
import sys
import os
from datetime import datetime
from pathlib import Path

from paths import HERMES_DATA, HL_COPY_REPORT
from hl_copy_db import get_db, init_db
from hl_leaderboard import scan_leaderboard, get_user_fills
from hl_fill_monitor import monitor_once, get_recent_fills, get_active_traders, check_trader_exits
from hl_signal_notifier import check_for_signals
from hl_copy_signal import run_hl_copy_signal
from hermes_constants import (
    HL_COPY_POLL_INTERVAL,
    HL_COPY_MIN_SCORE,
    HL_COPY_REPORT_PATH
)

REPORT_INTERVAL = 3600  # 1 hour
LEADERBOARD_REFRESH_INTERVAL = 21600  # 6 hours

def generate_report():
    """Generate markdown report for dashboard."""
    conn = get_db()
    try:
        # Get active traders
        traders = conn.execute("""
            SELECT * FROM traders 
            WHERE active = 1 AND score >= ?
            ORDER BY score DESC
        """, (HL_COPY_MIN_SCORE,)).fetchall()
        
        # Get recent trades (last 24h)
        recent_fills = conn.execute("""
            SELECT f.*, t.score 
            FROM trader_fills f
            JOIN traders t ON f.wallet = t.wallet
            WHERE f.time > ?
            ORDER BY f.time DESC
            LIMIT 20
        """, (int(time.time()) - 86400,)).fetchall()
        
        # Get stats
        total_fills = conn.execute("SELECT COUNT(*) as cnt FROM trader_fills").fetchone()['cnt']
        today_fills = conn.execute(
            "SELECT COUNT(*) as cnt FROM trader_fills WHERE time > ?",
            (int(time.time()) - 86400,)
        ).fetchone()['cnt']
    finally:
        conn.close()
    
    # Generate markdown
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    report = f"""# HL Copy Trading Report — {now}

## Active Traders ({len(traders)})

| Wallet | Score | PnL | WR | Trades | Pattern | Last Active |
|--------|-------|-----|-----|--------|---------|-------------|
"""
    
    for t in traders:
        wallet_short = t['wallet'][:10] + "..."
        last_active = datetime.fromtimestamp(t['last_updated']).strftime("%H:%M") if t['last_updated'] else "N/A"
        report += f"| {wallet_short} | {t['score']:.1f} | ${t['pnl_all_time']:.0f} | {t['win_rate']:.0%} | {t['trade_count']} | {t['pattern']} | {last_active} |\n"
    
    report += f"""
## Recent Trades (24h)

| Time | Trader | Coin | Side | Size | Price | PnL |
|------|--------|------|------|------|-------|-----|
"""
    
    for f in recent_fills:
        time_str = datetime.fromtimestamp(f['time'] / 1000).strftime("%H:%M") if f['time'] > 1e12 else datetime.fromtimestamp(f['time']).strftime("%H:%M")
        wallet_short = f['wallet'][:10] + "..."
        pnl_str = f"+${f['closed_pnl']:.2f}" if f['closed_pnl'] > 0 else f"-${abs(f['closed_pnl']):.2f}" if f['closed_pnl'] < 0 else "-"
        report += f"| {time_str} | {wallet_short} | {f['coin']} | {f['side']} | {f['sz']:.4f} | ${f['px']:.2f} | {pnl_str} |\n"
    
    report += f"""
## Statistics

- Total fills tracked: {total_fills}
- Fills in last 24h: {today_fills}
- Active traders: {len(traders)}
- Min score threshold: {HL_COPY_MIN_SCORE}

---
*Auto-generated by HL Copy Trading System*
"""
    
    # Write report (atomic)
    Path(HL_COPY_REPORT_PATH).parent.mkdir(parents=True, exist_ok=True)
    tmp_path = HL_COPY_REPORT_PATH + '.tmp'
    try:
        with open(tmp_path, 'w') as f:
            f.write(report)
        os.replace(tmp_path, HL_COPY_REPORT_PATH)
    except Exception as e:
        print(f"[report] Error writing: {e}")
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
    
    print(f"[report] Generated at {now}")

def run_once():
    """Run one complete cycle: scan, monitor, report."""
    print(f"\n{'='*60}")
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Running copy trading cycle")
    print('='*60)
    
    # Step 1: Monitor fills from tracked traders
    print("\n[1/5] Monitoring fills...")
    new_fills = monitor_once()
    
    if new_fills:
        print(f"  Found {len(new_fills)} new fills")
    else:
        print("  No new fills")
    
    # Step 1b: Check for trader exits to close our copy trades
    print("\n[1b/5] Checking for trader exits...")
    check_trader_exits(new_fills)
    
    # Step 1c: Sync trader_performance with closed trades
    print("\n[1c/5] Syncing trader performance...")
    from hl_fill_monitor import sync_trader_performance
    synced = sync_trader_performance()
    if synced:
        print(f"  Synced {synced} records")
    else:
        print("  All up to date")
    
    # Step 1d: Refresh leaderboard (every 6 hours)
    last_leaderboard_file = os.path.join(HERMES_DATA, 'hl_copy_last_leaderboard.txt')
    try:
        with open(last_leaderboard_file) as f:
            last_leaderboard = int(f.read().strip())
    except (FileNotFoundError, ValueError, OSError):
        last_leaderboard = 0
    
    if time.time() - last_leaderboard > LEADERBOARD_REFRESH_INTERVAL:
        print("\n[1d/5] Refreshing leaderboard...")
        try:
            traders = scan_leaderboard()
            print(f"  Scanned {len(traders)} traders")
            with open(last_leaderboard_file, 'w') as f:
                f.write(str(int(time.time())))
        except Exception as e:
            print(f"  Leaderboard refresh failed: {e}")
    else:
        remaining = int((LEADERBOARD_REFRESH_INTERVAL - (time.time() - last_leaderboard)) / 60)
        print(f"\n[1d/5] Leaderboard refresh in {remaining}m")
    
    # Step 2: Check for pro trader signals
    print("\n[2/5] Checking for pro trader signals...")
    signals = check_for_signals()
    
    if signals:
        print(f"  🚨 {len(signals)} signal(s) fired!")
    else:
        print("  No new pro trader signals")
    
    # Step 3: Generate pipeline signals from pro trades
    print("\n[3/5] Generating pipeline signals...")
    pipeline_signals = run_hl_copy_signal()
    
    if pipeline_signals:
        print(f"  📊 {len(pipeline_signals)} signal(s) written to pipeline")
    else:
        print("  No new pipeline signals")
    
    # Step 4: Generate report (every hour)
    last_report_file = os.path.join(HERMES_DATA, 'hl_copy_last_report.txt')
    try:
        with open(last_report_file) as f:
            last_report = int(f.read().strip())
    except (FileNotFoundError, ValueError, OSError):
        last_report = 0
    
    if time.time() - last_report > REPORT_INTERVAL:
        print("\n[4/5] Generating report...")
        generate_report()
        with open(last_report_file, 'w') as f:
            f.write(str(int(time.time())))
    else:
        print(f"\n[4/5] Report next in {int((REPORT_INTERVAL - (time.time() - last_report)) / 60)}m")
    
    # Step 5: Summary
    print("\n[5/5] Summary:")
    active = get_active_traders()
    print(f"  Active traders: {len(active)}")
    
    # Get today's stats
    conn = get_db()
    try:
        today = conn.execute(
            "SELECT COUNT(*) as cnt, SUM(closed_pnl) as pnl FROM trader_fills WHERE time > ?",
            (int(time.time()) - 86400,)
        ).fetchone()
    finally:
        conn.close()
    
    print(f"  Today's fills: {today['cnt']}")
    print(f"  Today's PnL: ${today['pnl']:.2f}" if today['pnl'] else "  Today's PnL: $0.00")

def run_daemon():
    """Run as daemon with periodic cycles."""
    print("[daemon] Starting HL Copy Trading daemon...")
    print(f"[daemon] Poll interval: {HL_COPY_POLL_INTERVAL}s")
    print(f"[daemon] Report interval: {REPORT_INTERVAL}s")
    print(f"[daemon] Press Ctrl+C to stop\n")
    
    while True:
        try:
            run_once()
            print(f"\n[daemon] Next cycle in {HL_COPY_POLL_INTERVAL}s...")
            time.sleep(HL_COPY_POLL_INTERVAL)
        except KeyboardInterrupt:
            print("\n[daemon] Stopping...")
            break
        except Exception as e:
            print(f"[daemon] Error: {e}")
            time.sleep(60)  # Wait longer on error

def main():
    init_db()
    
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == 'once':
            run_once()
        elif cmd == 'report':
            generate_report()
        elif cmd == 'scan':
            if len(sys.argv) > 2:
                wallet = sys.argv[2]
                from hl_leaderboard import scan_wallet
                trader = scan_wallet(wallet)
                if trader:
                    print(f"Score: {trader['score']}")
                    print(f"PnL: ${trader['pnl_all_time']:.0f}")
                    print(f"WR: {trader['win_rate']:.1%}")
                else:
                    print("Could not scan wallet")
        else:
            print(f"Unknown command: {cmd}")
            print("Usage: hl_copy_trader.py [once|daemon|report|scan <wallet>]")
    else:
        run_daemon()

if __name__ == "__main__":
    main()
