-- signals_hermes_runtime.db schema
-- Generated by git-master audit

CREATE TABLE signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT NOT NULL,
    direction TEXT NOT NULL,
    signal_type TEXT NOT NULL,
    source TEXT,
    confidence REAL NOT NULL,
    value REAL,
    price REAL,
    exchange TEXT DEFAULT 'hyperliquid',
    timeframe TEXT DEFAULT '1h',
    decision TEXT DEFAULT 'PENDING',
    decision_reason TEXT,
    executed INTEGER DEFAULT 0,
    z_score REAL,
    z_score_tier TEXT,
    momentum_state TEXT,
    rsi_14 REAL,
    macd_value REAL,
    macd_signal REAL,
    macd_hist REAL,
    leverage INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
, compact_rounds INTEGER DEFAULT 0, last_compact_at TEXT, survival_score REAL DEFAULT 0.0, learned_sl_multiplier REAL DEFAULT 1.0, review_count INTEGER DEFAULT 0);

CREATE TABLE momentum_cache (
    token TEXT PRIMARY KEY,
    phase TEXT,
    percentile_long REAL,
    percentile_short REAL,
    velocity REAL,
    avg_z REAL,
    z_direction TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
, momentum_state TEXT DEFAULT "neutral", state_confidence REAL DEFAULT 0.3);

CREATE TABLE token_intel (
    token TEXT PRIMARY KEY,
    exchange TEXT,
    max_leverage INTEGER,
    base_position_size REAL,
    open_positions INTEGER DEFAULT 0,
    last_signal_at TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cooldown_tracker (
    token TEXT NOT NULL,
    direction TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    PRIMARY KEY(token, direction)
);

CREATE TABLE decisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT NOT NULL,
    direction TEXT NOT NULL,
    confidence REAL NOT NULL,
    entry_price REAL,
    exchange TEXT,
    decision TEXT NOT NULL,
    reason TEXT,
    server TEXT DEFAULT 'Hermes',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signals_archive_20260331(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signals_archive_20260331_1622(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signals_archive_20260331_1627(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signals_archive_20260331_1718(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signals_archive_20260331_214839(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signals_archive_20260331_2224(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE signal_outcomes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                token TEXT NOT NULL,
                direction TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                is_win INTEGER NOT NULL,
                pnl_pct REAL NOT NULL,
                pnl_usdt REAL NOT NULL,
                confidence REAL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                closed_at TEXT DEFAULT CURRENT_TIMESTAMP
            );

CREATE TABLE signal_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT NOT NULL,
    direction TEXT NOT NULL,
    signal_type TEXT NOT NULL,
    compact_round INTEGER NOT NULL,
    survived INTEGER NOT NULL,  -- 1=survived this round, 0=compacted away
    score_before REAL,
    score_after REAL,
    reason TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signals_archive_20260401_0507(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT,
  compact_rounds INT,
  last_compact_at TEXT,
  survival_score REAL
);

CREATE TABLE signals_archive_20260401_0545(
  id INT,
  token TEXT,
  direction TEXT,
  signal_type TEXT,
  source TEXT,
  confidence REAL,
  value REAL,
  price REAL,
  exchange TEXT,
  timeframe TEXT,
  decision TEXT,
  decision_reason TEXT,
  executed INT,
  z_score REAL,
  z_score_tier TEXT,
  momentum_state TEXT,
  rsi_14 REAL,
  macd_value REAL,
  macd_signal REAL,
  macd_hist REAL,
  leverage INT,
  created_at TEXT,
  updated_at TEXT,
  compact_rounds INT,
  last_compact_at TEXT,
  survival_score REAL
);

CREATE TABLE review_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    git_commit TEXT,
    review_date TEXT,
    section TEXT,
    priority INTEGER DEFAULT 0,
    title TEXT,
    finding TEXT,
    file TEXT,
    line TEXT,
    fix TEXT,
    status TEXT DEFAULT "open",
    created_at TEXT
);

