-- brain PostgreSQL DB schema
-- Generated by git-master audit
-- Requires: PostgreSQL 14+, psycopg2, createdb brain

CREATE TABLE ab_results (
  id integer DEFAULT nextval('ab_results_id_seq'::regclass) NOT NULL,
  test_name text NOT NULL,
  variant_id text NOT NULL,
  trades integer DEFAULT 0 NULL,
  wins integer DEFAULT 0 NULL,
  losses integer DEFAULT 0 NULL,
  total_pnl_pct double precision DEFAULT 0 NULL,
  total_pnl_usdt double precision DEFAULT 0 NULL,
  avg_win_pct double precision DEFAULT 0 NULL,
  avg_loss_pct double precision DEFAULT 0 NULL,
  win_rate_pct double precision DEFAULT 0 NULL,
  avg_r double precision DEFAULT 0 NULL,
  updated_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE loss_cooldowns (
  token text NOT NULL,
  direction text NULL,
  expires_at timestamp with time zone NULL,
  loss_pct real NULL
);

CREATE TABLE trades (
  id integer DEFAULT nextval('trades_id_seq'::regclass) NOT NULL,
  trade_id integer NULL,
  token character varying NULL,
  pair character varying NULL,
  strategy character varying NULL,
  amount_usdt numeric NULL,
  entry_price numeric NULL,
  stop_loss numeric NULL,
  target numeric NULL,
  exit_price numeric NULL,
  pnl_usdt numeric NULL,
  pnl_pct numeric NULL,
  status character varying NULL,
  exchange character varying NULL,
  signal_reason text NULL,
  notes text NULL,
  open_time timestamp without time zone NULL,
  close_time timestamp without time zone NULL,
  created_at timestamp without time zone DEFAULT now() NULL,
  current_price numeric NULL,
  last_updated timestamp without time zone NULL,
  exit_conditions text NULL,
  regime text NULL,
  updated_at timestamp without time zone DEFAULT now() NULL,
  paper boolean DEFAULT true NULL,
  server character varying DEFAULT 'Tokyo'::character varying NULL,
  signal character varying NULL,
  confidence numeric NULL,
  leverage integer DEFAULT 10 NULL,
  token_address character varying NULL,
  learnings text NULL,
  fees text NULL,
  direction text DEFAULT 'LONG'::text NULL,
  short_signal text NULL,
  chain character varying DEFAULT 'hyperliquid'::character varying NULL,
  trailing_stop_pct numeric NULL,
  trailing_stop_price numeric NULL,
  partial_exit numeric NULL,
  sl_distance double precision DEFAULT 0.005 NULL,
  trailing_threshold double precision DEFAULT 0.02 NULL,
  sl_group character varying DEFAULT 'control'::character varying NULL,
  experiment text NULL,
  exit_reason character varying NULL,
  missed_opportunity boolean DEFAULT false NULL,
  trailing_activated boolean DEFAULT false NULL,
  highest_price numeric DEFAULT 0 NULL,
  entry_rsi_14 numeric NULL,
  entry_macd_hist numeric NULL,
  entry_atr_14 numeric NULL,
  entry_bb_position numeric NULL,
  entry_slope_4h numeric NULL,
  entry_regime_4h character varying NULL,
  entry_trend character varying NULL,
  features_recorded boolean DEFAULT false NULL,
  predicted_return character varying NULL,
  actual_return numeric NULL,
  entry_fear_greed integer NULL,
  tp_multiplier numeric DEFAULT 10 NULL,
  peak_price numeric NULL,
  close_reason character varying NULL,
  breakeven_activated boolean DEFAULT false NULL,
  entry_timing character varying NULL,
  hype_pnl_usdt numeric DEFAULT 0 NULL,
  hype_pnl_pct numeric DEFAULT 0 NULL,
  lowest_price numeric NULL,
  trailing_activation real NULL,
  trailing_distance real NULL,
  hl_entry_price numeric DEFAULT 0 NULL,
  hl_exit_price numeric DEFAULT 0 NULL,
  trailing_phase2_dist real NULL
);

CREATE TABLE bookmarks (
  id integer DEFAULT nextval('bookmarks_id_seq'::regclass) NOT NULL,
  url text NOT NULL,
  title character varying NULL,
  description text NULL,
  category character varying NULL,
  tags ARRAY NULL,
  created_at timestamp without time zone DEFAULT now() NULL,
  updated_at timestamp without time zone NULL,
  created_by character varying NULL,
  favicon text NULL,
  is_favorite boolean DEFAULT false NULL,
  click_count integer DEFAULT 0 NULL,
  summary text NULL
);

CREATE TABLE thoughts (
  id integer DEFAULT nextval('thoughts_id_seq'::regclass) NOT NULL,
  content text NOT NULL,
  created_at timestamp without time zone DEFAULT now() NULL,
  source character varying NULL,
  session_id character varying NULL,
  embedding USER-DEFINED NULL,
  category text DEFAULT 'general'::text NULL,
  status text DEFAULT 'active'::text NULL,
  parent_id integer NULL,
  completed_at timestamp without time zone NULL,
  tags ARRAY NULL,
  title character varying NULL
);

CREATE TABLE trade_patterns (
  id integer DEFAULT nextval('trade_patterns_id_seq'::regclass) NOT NULL,
  token text NULL,
  side text NULL,
  regime text DEFAULT 'unknown'::text NULL,
  pattern_name text NULL,
  confidence real DEFAULT 0.5 NULL,
  adjustment jsonb NULL,
  sample_count integer DEFAULT 1 NULL,
  created_at timestamp without time zone DEFAULT now() NULL,
  last_seen timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE signal_cooldowns (
  token text NOT NULL,
  expires_at timestamp with time zone NULL,
  reason text NULL,
  direction text NOT NULL
);

CREATE TABLE hyperliquid_trades (
  id integer DEFAULT nextval('hyperliquid_trades_id_seq'::regclass) NOT NULL,
  trade_id character varying NULL,
  symbol character varying NULL,
  side character varying NULL,
  size numeric NULL,
  price numeric NULL,
  value_usd numeric NULL,
  fee numeric NULL,
  order_type character varying NULL,
  status character varying NULL,
  filled_at timestamp without time zone NULL,
  created_at timestamp without time zone DEFAULT now() NULL,
  metadata jsonb NULL
);

CREATE TABLE thought_links (
  id integer DEFAULT nextval('thought_links_id_seq'::regclass) NOT NULL,
  source_id integer NULL,
  target_id integer NULL,
  link_type character varying DEFAULT 'related'::character varying NULL,
  created_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE meta_tags (
  id integer DEFAULT nextval('meta_tags_id_seq'::regclass) NOT NULL,
  thought_id integer NULL,
  tag character varying NOT NULL,
  created_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE services (
  id integer DEFAULT nextval('services_id_seq'::regclass) NOT NULL,
  name character varying NOT NULL,
  type character varying NULL,
  script character varying NULL,
  server character varying NULL,
  runtime jsonb NULL,
  config jsonb NULL,
  description text NULL,
  created_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE metadata (
  id integer DEFAULT nextval('metadata_id_seq'::regclass) NOT NULL,
  thought_id integer NULL,
  key character varying NOT NULL,
  value text NOT NULL,
  created_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE token_blocklist (
  id integer DEFAULT nextval('token_blocklist_id_seq'::regclass) NOT NULL,
  token character varying NOT NULL,
  reason text NULL,
  added_at timestamp without time zone DEFAULT now() NULL
);

CREATE TABLE signal_cooldowns_old (
  token text NOT NULL,
  direction text NULL,
  expires_at timestamp with time zone NULL,
  reason text NULL
);

CREATE TABLE momentum_cache (
  token text NOT NULL,
  rsi_14 real NULL,
  macd_hist real NULL,
  atr_14 real NULL,
  bb_position real NULL,
  slope_4h real NULL,
  regime_4h text NULL,
  trend text NULL,
  updated_at timestamp with time zone DEFAULT now() NULL
);

